steps:
  # Étape 0 : Récupérer .env.production depuis Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Récupération du .env.production depuis Secret Manager"
        gcloud secrets versions access latest --secret=frontend-env-production > .env.production

  # Étape 1 : Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kode-461516/kode-pos-frontend', 'src/']

  # Étape 2 : Push de l’image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kode-461516/kode-pos-frontend']

  # Étape 3 : Déploiement Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'aurabe-frontend',
        '--image', 'gcr.io/kode-461516/kode-pos-frontend',
        '--region', 'us-east1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '80'
      ]

images:
  - gcr.io/kode-461516/kode-pos-frontend

# ✅ Logging + service account
options:
  logging: CLOUD_LOGGING_ONLY

# ✅ Ici à la RACINE
serviceAccount: 274796274461-compute@developer.gserviceaccount.com
